/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Gracia Sanchez
 */
public class pacienteFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form pacienteFrame
     */
    public pacienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panelClienteDatos5 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtNombreProductos = new javax.swing.JTextField();
        txtIDProductos = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        txtBuscadorPaciente = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(1190, 570));
        setPreferredSize(new java.awt.Dimension(1190, 570));

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1196, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Proveedores", jPanel1);

        panelClienteDatos5.setBackground(new java.awt.Color(147, 175, 93));
        panelClienteDatos5.setEnabled(false);
        panelClienteDatos5.setFocusCycleRoot(true);
        panelClienteDatos5.setMaximumSize(new java.awt.Dimension(750, 665));
        panelClienteDatos5.setMinimumSize(new java.awt.Dimension(750, 665));
        panelClienteDatos5.setPreferredSize(new java.awt.Dimension(750, 665));
        panelClienteDatos5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setText("Descripción :");
        panelClienteDatos5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, 34));

        jLabel66.setText("ID :");
        panelClienteDatos5.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, 34));

        jLabel67.setText("Nombre :");
        panelClienteDatos5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 34));
        panelClienteDatos5.add(txtNombreProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 201, -1));
        panelClienteDatos5.add(txtIDProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 201, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/guardar_1.png"))); // NOI18N
        panelClienteDatos5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 86, -1));
        panelClienteDatos5.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 20, 1196));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelClienteDatos5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jButton1.setText("Foto");
        panelClienteDatos5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 202, -1));

        jLabel1.setText("Código:");
        panelClienteDatos5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jLabel2.setText("jLabel2");
        panelClienteDatos5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jLabel3.setText("jLabel3");
        panelClienteDatos5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel4.setText("jLabel4");
        panelClienteDatos5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        jLabel5.setText("jLabel5");
        panelClienteDatos5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        jLabel6.setText("jLabel6");
        panelClienteDatos5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, -1, -1));

        jLabel7.setText("jLabel7");
        panelClienteDatos5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 750, -1, -1));

        jLabel8.setText("jLabel8");
        panelClienteDatos5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, -1, -1));

        jLabel9.setText("jLabel9");
        panelClienteDatos5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 800, -1, -1));

        jLabel10.setText("jLabel10");
        panelClienteDatos5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 830, -1, -1));

        jLabel11.setText("jLabel9");
        panelClienteDatos5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 770, -1, -1));

        jLabel12.setText("jLabel10");
        panelClienteDatos5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 800, -1, -1));

        jLabel13.setText("jLabel1");
        panelClienteDatos5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 870, -1, -1));

        jLabel14.setText("jLabel2");
        panelClienteDatos5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 900, -1, -1));

        jLabel15.setText("jLabel3");
        panelClienteDatos5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 930, -1, -1));

        jLabel16.setText("jLabel4");
        panelClienteDatos5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 960, -1, -1));

        jLabel17.setText("jLabel5");
        panelClienteDatos5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 990, -1, -1));

        jLabel18.setText("jLabel6");
        panelClienteDatos5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1020, -1, -1));

        jLabel19.setText("jLabel7");
        panelClienteDatos5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1050, -1, -1));

        jLabel20.setText("jLabel8");
        panelClienteDatos5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1090, -1, -1));

        jLabel21.setText("jLabel9");
        panelClienteDatos5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1070, -1, -1));

        jLabel22.setText("jLabel10");
        panelClienteDatos5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1090, -1, -1));

        jLabel23.setText("jLabel1");
        panelClienteDatos5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 830, -1, -1));

        jLabel24.setText("jLabel2");
        panelClienteDatos5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 860, -1, -1));

        jLabel25.setText("jLabel3");
        panelClienteDatos5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 890, -1, -1));

        jLabel26.setText("jLabel4");
        panelClienteDatos5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 920, -1, -1));

        jLabel27.setText("jLabel5");
        panelClienteDatos5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 950, -1, -1));

        jLabel28.setText("jLabel6");
        panelClienteDatos5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 980, -1, -1));

        jLabel29.setText("jLabel7");
        panelClienteDatos5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1010, -1, -1));

        jLabel30.setText("jLabel8");
        panelClienteDatos5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1040, -1, -1));

        jLabel31.setText("jLabel8");
        panelClienteDatos5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, -1, -1));

        jLabel32.setText("jLabel9");
        panelClienteDatos5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 720, -1, -1));

        jLabel33.setText("jLabel10");
        panelClienteDatos5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 750, -1, -1));

        jLabel34.setText("jLabel1");
        panelClienteDatos5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        jLabel35.setText("jLabel2");
        panelClienteDatos5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        jLabel36.setText("jLabel3");
        panelClienteDatos5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        jLabel37.setText("jLabel4");
        panelClienteDatos5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, -1, -1));

        jLabel38.setText("jLabel5");
        panelClienteDatos5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, -1, -1));

        jLabel39.setText("jLabel6");
        panelClienteDatos5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, -1, -1));

        jLabel40.setText("jLabel7");
        panelClienteDatos5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, -1, -1));
        panelClienteDatos5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 201, -1));
        panelClienteDatos5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 201, -1));
        panelClienteDatos5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 201, -1));
        panelClienteDatos5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 201, -1));
        panelClienteDatos5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, 201, -1));
        panelClienteDatos5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 720, 201, -1));
        panelClienteDatos5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 750, 201, -1));
        panelClienteDatos5.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 780, 201, -1));
        panelClienteDatos5.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 820, 201, -1));
        panelClienteDatos5.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 860, 201, -1));
        panelClienteDatos5.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 900, 201, -1));
        panelClienteDatos5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 940, 201, -1));
        panelClienteDatos5.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 970, 201, -1));
        panelClienteDatos5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1010, 201, -1));
        panelClienteDatos5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1050, 201, -1));
        panelClienteDatos5.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1090, 201, -1));
        panelClienteDatos5.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 790, 201, -1));
        panelClienteDatos5.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 820, 201, -1));
        panelClienteDatos5.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 860, 201, -1));
        panelClienteDatos5.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 890, 201, -1));
        panelClienteDatos5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 930, 201, -1));
        panelClienteDatos5.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 970, 201, -1));
        panelClienteDatos5.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1000, 201, -1));
        panelClienteDatos5.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1040, 201, -1));
        panelClienteDatos5.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1080, 201, -1));
        panelClienteDatos5.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 220, -1));
        panelClienteDatos5.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 220, -1));
        panelClienteDatos5.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 220, -1));
        panelClienteDatos5.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 220, -1));
        panelClienteDatos5.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 220, -1));
        panelClienteDatos5.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 220, -1));
        panelClienteDatos5.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 710, 220, -1));
        panelClienteDatos5.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 740, 220, -1));

        jTabbedPane2.addTab("Productos", panelClienteDatos5);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 410));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Raza"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePacientes);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 410, 490));

        txtBuscadorPaciente.setText("Buscar . . .");
        txtBuscadorPaciente.setPreferredSize(new java.awt.Dimension(260, 260));
        txtBuscadorPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscadorPacienteMouseEntered(evt);
            }
        });
        txtBuscadorPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorPacienteActionPerformed(evt);
            }
        });
        jPanel4.add(txtBuscadorPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 260, 30));

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/anadir-usuario-icono-4000-32.png"))); // NOI18N
        btnAgregarCliente.setPreferredSize(new java.awt.Dimension(70, 30));
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 70, 30));

        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/eliminar-usuario-icono-7266-32.png"))); // NOI18N
        jPanel4.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorPacienteMouseClicked

    private void txtBuscadorPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorPacienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorPacienteMouseEntered

    private void txtBuscadorPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorPacienteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTable jTablePacientes;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField17;
    public javax.swing.JTextField jTextField18;
    public javax.swing.JTextField jTextField19;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField20;
    public javax.swing.JTextField jTextField21;
    public javax.swing.JTextField jTextField22;
    public javax.swing.JTextField jTextField23;
    public javax.swing.JTextField jTextField24;
    public javax.swing.JTextField jTextField25;
    public javax.swing.JTextField jTextField26;
    public javax.swing.JTextField jTextField27;
    public javax.swing.JTextField jTextField28;
    public javax.swing.JTextField jTextField29;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField30;
    public javax.swing.JTextField jTextField31;
    public javax.swing.JTextField jTextField32;
    public javax.swing.JTextField jTextField33;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelClienteDatos5;
    public javax.swing.JTextField txtBuscadorPaciente;
    public javax.swing.JTextField txtIDProductos;
    public javax.swing.JTextField txtNombreProductos;
    // End of variables declaration//GEN-END:variables
}
