/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Gracia Sanchez
 */
public class pacienteFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form pacienteFrame
     */
    public pacienteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        t = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        txtNombrePacientes = new javax.swing.JTextField();
        btnGuardarPaciente = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotas = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCaracter = new javax.swing.JTextArea();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextArea27 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextArea28 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextArea29 = new javax.swing.JTextArea();
        jScrollPane31 = new javax.swing.JScrollPane();
        jTextArea30 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        jTextArea31 = new javax.swing.JTextArea();
        jScrollPane33 = new javax.swing.JScrollPane();
        jTextArea32 = new javax.swing.JTextArea();
        jScrollPane34 = new javax.swing.JScrollPane();
        jTextArea33 = new javax.swing.JTextArea();
        jScrollPane35 = new javax.swing.JScrollPane();
        jTextArea34 = new javax.swing.JTextArea();
        jScrollPane36 = new javax.swing.JScrollPane();
        jTextArea35 = new javax.swing.JTextArea();
        jScrollPane37 = new javax.swing.JScrollPane();
        jTextArea36 = new javax.swing.JTextArea();
        jScrollPane38 = new javax.swing.JScrollPane();
        jTextArea37 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane39 = new javax.swing.JScrollPane();
        jTextAre25 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        txtBuscadorPaciente = new javax.swing.JTextField();
        btnAgregarPaciente = new javax.swing.JButton();
        btnEliminarPaciente = new javax.swing.JButton();

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(1190, 570));
        setPreferredSize(new java.awt.Dimension(1190, 570));

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        t.setBackground(new java.awt.Color(147, 175, 93));
        t.setEnabled(false);
        t.setFocusCycleRoot(true);
        t.setMaximumSize(new java.awt.Dimension(750, 665));
        t.setMinimumSize(new java.awt.Dimension(750, 665));
        t.setPreferredSize(new java.awt.Dimension(750, 10000));
        t.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setText("Nombre :");
        t.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 20));
        t.add(txtNombrePacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 270, -1));

        btnGuardarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/guardar_1.png"))); // NOI18N
        btnGuardarPaciente.setPreferredSize(new java.awt.Dimension(105, 36));
        t.add(btnGuardarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 86, -1));
        t.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 90, 16, 4110));

        jButton1.setText("Foto");
        t.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 202, -1));

        jLabel2.setText("Especie :");
        t.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel3.setText("Raza :");
        t.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel4.setText("Sexo :");
        t.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel5.setText("Edad :");
        t.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel6.setText("Peso :");
        t.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        jLabel7.setText("Nacimiento :");
        t.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel8.setText("Fecha :");
        t.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        jLabel9.setText("Desde :");
        t.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, -1));

        jLabel10.setText("Hasta :");
        t.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, -1, -1));

        jLabel11.setText("Forma de Abdomen :");
        t.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2000, 100, 20));

        jLabel13.setText("DNI :");
        t.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, -1, -1));

        jLabel14.setText("Caracter :");
        t.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, -1, -1));

        jLabel15.setText("Ejercicio :");
        t.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 800, -1, -1));

        jLabel16.setText("Alimentación :");
        t.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 830, -1, -1));

        jLabel17.setText("Color :");
        t.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 920, -1, -1));

        jLabel18.setText("Piel :");
        t.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 950, -1, -1));

        jLabel19.setText("Pelo :");
        t.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 980, -1, -1));

        jLabel20.setText("Cabeza :");
        t.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1010, -1, 20));

        jLabel21.setText("Ano :");
        t.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 2900, -1, 20));

        jLabel22.setText("Orina :");
        t.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 2990, -1, 20));

        jLabel23.setText("Abdomen Palpación :");
        t.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2090, -1, 20));

        jLabel25.setText("Auscultación intestinal :");
        t.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2360, -1, 20));

        jLabel26.setText("Ondulación intestinal :");
        t.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2450, -1, 30));

        jLabel27.setText("Extremidades :");
        t.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2540, 80, 20));

        jLabel28.setText("Sistema Nervioso :");
        t.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2630, 90, 20));

        jLabel29.setText("Genitales :");
        t.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2720, -1, 20));

        jLabel30.setText("Recto :");
        t.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 2810, -1, 20));

        jLabel31.setText("Torax :");
        t.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1730, 40, -1));

        jLabel32.setText("Aparato Locomotor :");
        t.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1820, 100, 20));

        jLabel33.setText("Conciencia :");
        t.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1910, -1, 20));

        jLabel34.setText("Cuello :");
        t.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1100, -1, 10));

        jLabel35.setText("Oidos :");
        t.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1190, -1, 20));

        jLabel36.setText("Labios :");
        t.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1270, -1, 40));

        jLabel37.setText("Dientes :");
        t.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1360, -1, 40));

        jLabel38.setText("Lengua :");
        t.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1460, -1, 20));

        jLabel39.setText("Boca :");
        t.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1550, -1, 20));

        jLabel40.setText("Masticadores :");
        t.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1640, 70, 20));
        t.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 270, -1));
        t.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 270, -1));

        jLabel41.setText("Heces :");
        t.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 3080, -1, 20));

        jLabel42.setText("Notas :");
        t.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 3980, -1, 20));

        jLabel43.setText("Enfermedades :");
        t.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 3170, 80, 20));

        jLabel44.setText("Cirugias Previas :");
        t.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 3260, 90, 20));

        jLabel45.setText("Esterilización :");
        t.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 3350, 70, 20));

        jLabel46.setText("Vacunación :");
        t.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 3440, -1, 20));

        jLabel47.setText("Desparasitación :");
        t.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 3530, -1, 20));

        jLabel48.setText("Leishmaniosis :");
        t.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 3620, -1, 20));

        jLabel49.setText("Habitat :");
        t.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 3710, 50, 20));

        jLabel50.setText("Entorno :");
        t.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 3800, 50, 20));

        jLabel51.setText("Viajes :");
        t.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 3890, -1, 20));

        jTextAreaNotas.setColumns(20);
        jTextAreaNotas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNotas);

        t.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3980, 400, 80));
        t.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 270, -1));
        t.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 270, -1));
        t.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 270, -1));
        t.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 270, -1));
        t.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 270, -1));
        t.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 270, -1));
        t.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 270, -1));
        t.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 980, 270, -1));
        t.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, 270, -1));

        jTextAreaCaracter.setColumns(20);
        jTextAreaCaracter.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCaracter);

        t.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, 400, 80));
        t.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 800, 270, -1));
        t.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 920, 270, -1));
        t.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 950, 270, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        t.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 830, 400, 80));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        t.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1010, 400, 80));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        t.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1100, 400, 80));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane7.setViewportView(jTextArea6);

        t.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1190, 400, 80));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane8.setViewportView(jTextArea7);

        t.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1280, 400, 80));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane9.setViewportView(jTextArea8);

        t.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1370, 400, 80));

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane10.setViewportView(jTextArea9);

        t.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1460, 400, 80));

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jScrollPane11.setViewportView(jTextArea10);

        t.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1550, 400, 80));

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jScrollPane12.setViewportView(jTextArea11);

        t.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1640, 400, 80));

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jScrollPane13.setViewportView(jTextArea12);

        t.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1730, 400, 80));

        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jScrollPane14.setViewportView(jTextArea13);

        t.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1820, 400, 80));

        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);
        jScrollPane15.setViewportView(jTextArea14);

        t.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1910, 400, 80));

        jLabel52.setText("Intestino Percusión :");
        t.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2270, -1, 20));

        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        jScrollPane16.setViewportView(jTextArea15);

        t.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2000, 400, 80));

        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        jScrollPane17.setViewportView(jTextArea16);

        t.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2090, 400, 80));

        jLabel53.setText("Abdomen Profundo :");
        t.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2180, -1, 20));

        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        jScrollPane18.setViewportView(jTextArea17);

        t.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2180, 400, 80));

        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        jScrollPane19.setViewportView(jTextArea18);

        t.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2270, 400, 80));

        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jScrollPane20.setViewportView(jTextArea19);

        t.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2360, 400, 80));

        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);
        jScrollPane21.setViewportView(jTextArea20);

        t.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2450, 400, 80));

        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jScrollPane22.setViewportView(jTextArea21);

        t.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2540, 400, 80));

        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);
        jScrollPane23.setViewportView(jTextArea22);

        t.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2630, 400, 80));

        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);
        jScrollPane24.setViewportView(jTextArea23);

        t.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2720, 400, 80));

        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);
        jScrollPane25.setViewportView(jTextArea24);

        t.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2810, 400, 80));

        jTextArea27.setColumns(20);
        jTextArea27.setRows(5);
        jScrollPane26.setViewportView(jTextArea27);

        t.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2990, 400, 80));

        jTextArea28.setColumns(20);
        jTextArea28.setRows(5);
        jScrollPane29.setViewportView(jTextArea28);

        t.add(jScrollPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3080, 400, 80));

        jTextArea29.setColumns(20);
        jTextArea29.setRows(5);
        jScrollPane30.setViewportView(jTextArea29);

        t.add(jScrollPane30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3170, 400, 80));

        jTextArea30.setColumns(20);
        jTextArea30.setRows(5);
        jScrollPane31.setViewportView(jTextArea30);

        t.add(jScrollPane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3260, 400, 80));

        jTextArea31.setColumns(20);
        jTextArea31.setRows(5);
        jScrollPane32.setViewportView(jTextArea31);

        t.add(jScrollPane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3350, 400, 80));

        jTextArea32.setColumns(20);
        jTextArea32.setRows(5);
        jScrollPane33.setViewportView(jTextArea32);

        t.add(jScrollPane33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3440, 400, 80));

        jTextArea33.setColumns(20);
        jTextArea33.setRows(5);
        jScrollPane34.setViewportView(jTextArea33);

        t.add(jScrollPane34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3530, 400, 80));

        jTextArea34.setColumns(20);
        jTextArea34.setRows(5);
        jScrollPane35.setViewportView(jTextArea34);

        t.add(jScrollPane35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3620, 400, 80));

        jTextArea35.setColumns(20);
        jTextArea35.setRows(5);
        jScrollPane36.setViewportView(jTextArea35);

        t.add(jScrollPane36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3710, 400, 80));

        jTextArea36.setColumns(20);
        jTextArea36.setRows(5);
        jScrollPane37.setViewportView(jTextArea36);

        t.add(jScrollPane37, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3800, 400, 80));

        jTextArea37.setColumns(20);
        jTextArea37.setRows(5);
        jScrollPane38.setViewportView(jTextArea37);

        t.add(jScrollPane38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 3890, 400, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        t.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 200, 190));

        jTextAre25.setColumns(20);
        jTextAre25.setRows(5);
        jScrollPane39.setViewportView(jTextAre25);

        t.add(jScrollPane39, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 2900, 400, 80));

        jTabbedPane2.addTab("Paciente", t);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Proveedores", jPanel1);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 410));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Raza"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePacientes);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 410, 490));

        txtBuscadorPaciente.setText("Buscar . . .");
        txtBuscadorPaciente.setPreferredSize(new java.awt.Dimension(260, 260));
        txtBuscadorPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscadorPacienteMouseEntered(evt);
            }
        });
        txtBuscadorPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorPacienteActionPerformed(evt);
            }
        });
        jPanel4.add(txtBuscadorPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 260, 30));

        btnAgregarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/anadir-usuario-icono-4000-32.png"))); // NOI18N
        btnAgregarPaciente.setPreferredSize(new java.awt.Dimension(70, 30));
        btnAgregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPacienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 70, 30));

        btnEliminarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/eliminar-usuario-icono-7266-32.png"))); // NOI18N
        jPanel4.add(btnEliminarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, Short.MAX_VALUE)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorPacienteMouseClicked

    private void txtBuscadorPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorPacienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorPacienteMouseEntered

    private void txtBuscadorPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorPacienteActionPerformed

    private void btnAgregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarPaciente;
    public javax.swing.JButton btnEliminarPaciente;
    public javax.swing.JButton btnGuardarPaciente;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane29;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTable jTablePacientes;
    public javax.swing.JTextArea jTextAre25;
    public javax.swing.JTextArea jTextArea10;
    public javax.swing.JTextArea jTextArea11;
    public javax.swing.JTextArea jTextArea12;
    public javax.swing.JTextArea jTextArea13;
    public javax.swing.JTextArea jTextArea14;
    public javax.swing.JTextArea jTextArea15;
    public javax.swing.JTextArea jTextArea16;
    public javax.swing.JTextArea jTextArea17;
    public javax.swing.JTextArea jTextArea18;
    public javax.swing.JTextArea jTextArea19;
    public javax.swing.JTextArea jTextArea20;
    public javax.swing.JTextArea jTextArea21;
    public javax.swing.JTextArea jTextArea22;
    public javax.swing.JTextArea jTextArea23;
    public javax.swing.JTextArea jTextArea24;
    public javax.swing.JTextArea jTextArea27;
    public javax.swing.JTextArea jTextArea28;
    public javax.swing.JTextArea jTextArea29;
    public javax.swing.JTextArea jTextArea3;
    public javax.swing.JTextArea jTextArea30;
    public javax.swing.JTextArea jTextArea31;
    public javax.swing.JTextArea jTextArea32;
    public javax.swing.JTextArea jTextArea33;
    public javax.swing.JTextArea jTextArea34;
    public javax.swing.JTextArea jTextArea35;
    public javax.swing.JTextArea jTextArea36;
    public javax.swing.JTextArea jTextArea37;
    public javax.swing.JTextArea jTextArea4;
    public javax.swing.JTextArea jTextArea5;
    public javax.swing.JTextArea jTextArea6;
    public javax.swing.JTextArea jTextArea7;
    public javax.swing.JTextArea jTextArea8;
    public javax.swing.JTextArea jTextArea9;
    public javax.swing.JTextArea jTextAreaCaracter;
    public javax.swing.JTextArea jTextAreaNotas;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    private javax.swing.JPanel t;
    public javax.swing.JTextField txtBuscadorPaciente;
    public javax.swing.JTextField txtNombrePacientes;
    // End of variables declaration//GEN-END:variables
}
