/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Roberto
 */
public class trabajadoresFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form trabajadoresFrame
     */
    public trabajadoresFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListadoCliente = new javax.swing.JPanel();
        txtBuscadorTrabajadores = new javax.swing.JTextField();
        scrollTableCliente = new javax.swing.JScrollPane();
        jTableTrabajadores = new javax.swing.JTable();
        btnAgregarTrabajadores = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarTrabajadores = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelClienteDatos = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtApellidosTrabajadores = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txtNombreTrabajadores = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txtDireccionTrabajadores = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtTelefonoTrabajadores = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txtMovilTrabajadores = new javax.swing.JTextField();
        txtDNITrabajadores = new javax.swing.JTextField();
        txtFechaTrabajadores = new javax.swing.JTextField();
        txtCodigoPTrabajadores = new javax.swing.JTextField();
        txtEmailTrabajadores = new javax.swing.JTextField();
        txtFechaITrabajadores = new javax.swing.JTextField();
        txtProvinciaTrabajadores = new javax.swing.JTextField();
        btnGuardarTrabajadores = new javax.swing.JButton();
        scrollNotaCliente = new javax.swing.JScrollPane();
        TextAreaTrabajadores = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel2 = new javax.swing.JLabel();
        txtSalarioTrabajadores = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1190, 570));
        setPreferredSize(new java.awt.Dimension(1190, 570));

        panelListadoCliente.setMinimumSize(new java.awt.Dimension(500, 410));
        panelListadoCliente.setPreferredSize(new java.awt.Dimension(500, 410));
        panelListadoCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscadorTrabajadores.setText("Buscar . . .");
        txtBuscadorTrabajadores.setPreferredSize(new java.awt.Dimension(260, 260));
        txtBuscadorTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorTrabajadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscadorTrabajadoresMouseEntered(evt);
            }
        });
        txtBuscadorTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorTrabajadoresActionPerformed(evt);
            }
        });
        panelListadoCliente.add(txtBuscadorTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 260, 30));

        scrollTableCliente.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollTableCliente.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollTableCliente.setPreferredSize(new java.awt.Dimension(410, 615));

        jTableTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTrabajadores.setOpaque(false);
        scrollTableCliente.setViewportView(jTableTrabajadores);

        panelListadoCliente.add(scrollTableCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 490));

        btnAgregarTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/anadir-usuario-icono-4000-32.png"))); // NOI18N
        btnAgregarTrabajadores.setPreferredSize(new java.awt.Dimension(70, 30));
        btnAgregarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTrabajadoresActionPerformed(evt);
            }
        });
        panelListadoCliente.add(btnAgregarTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/fondo2_1.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(450, 900));
        jLabel3.setMinimumSize(new java.awt.Dimension(250, 600));
        panelListadoCliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 490));

        btnEliminarTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/eliminar-usuario-icono-7266-32.png"))); // NOI18N
        panelListadoCliente.add(btnEliminarTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, 30));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1160, 682));

        panelClienteDatos.setBackground(new java.awt.Color(147, 175, 93));
        panelClienteDatos.setMaximumSize(new java.awt.Dimension(750, 665));
        panelClienteDatos.setPreferredSize(new java.awt.Dimension(750, 665));

        jLabel50.setText("Codigo Postal:");

        jLabel51.setText("Provincia :");

        jLabel52.setText("Email :");

        jLabel53.setText("Fecha Nacimiento:");

        jLabel54.setText("Fecha Ingreso :");

        jLabel55.setText("DNI : ");

        jLabel56.setText("Nombre :");

        jLabel57.setText("Apellidos :");

        jLabel58.setText("Dirección :");

        txtDireccionTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionTrabajadoresActionPerformed(evt);
            }
        });

        jLabel59.setText("Teléfono :");

        txtTelefonoTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoTrabajadoresjTextField3ActionPerformed(evt);
            }
        });

        jLabel60.setText("Móvil :");

        txtDNITrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNITrabajadoresActionPerformed(evt);
            }
        });

        txtFechaITrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaITrabajadoresActionPerformed(evt);
            }
        });

        btnGuardarTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesBotones/guardar_1.png"))); // NOI18N

        scrollNotaCliente.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollNotaCliente.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollNotaCliente.setViewportView(TextAreaTrabajadores);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Notas :");

        jLabel2.setText("Salario :");

        javax.swing.GroupLayout panelClienteDatosLayout = new javax.swing.GroupLayout(panelClienteDatos);
        panelClienteDatos.setLayout(panelClienteDatosLayout);
        panelClienteDatosLayout.setHorizontalGroup(
            panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteDatosLayout.createSequentialGroup()
                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteDatosLayout.createSequentialGroup()
                        .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel60))
                                    .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel57))
                                            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel58))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteDatosLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel59))))
                                .addGap(28, 28, 28)
                                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccionTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidosTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoTrabajadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMovilTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDNITrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteDatosLayout.createSequentialGroup()
                                                        .addGap(45, 45, 45)
                                                        .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteDatosLayout.createSequentialGroup()
                                                        .addGap(7, 7, 7)
                                                        .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteDatosLayout.createSequentialGroup()
                                                        .addGap(26, 26, 26)
                                                        .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCodigoPTrabajadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailTrabajadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaTrabajadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaITrabajadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProvinciaTrabajadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalarioTrabajadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteDatosLayout.createSequentialGroup()
                                .addGap(44, 596, Short.MAX_VALUE)
                                .addComponent(btnGuardarTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelClienteDatosLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(scrollNotaCliente)))
                        .addGap(57, 57, 57))
                    .addGroup(panelClienteDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(345, 345, 345)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelClienteDatosLayout.setVerticalGroup(
            panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnGuardarTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNITrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSalarioTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(txtCodigoPTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58)
                    .addComponent(txtFechaTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(jLabel54)
                    .addComponent(txtFechaITrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelClienteDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMovilTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProvinciaTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(scrollNotaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Trabajadores", panelClienteDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelListadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListadoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorTrabajadoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorTrabajadoresMouseClicked

    private void txtBuscadorTrabajadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorTrabajadoresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorTrabajadoresMouseEntered

    private void txtBuscadorTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorTrabajadoresActionPerformed

    private void btnAgregarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarTrabajadoresActionPerformed

    private void txtFechaITrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaITrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaITrabajadoresActionPerformed

    private void txtDNITrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNITrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNITrabajadoresActionPerformed

    private void txtTelefonoTrabajadoresjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoTrabajadoresjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoTrabajadoresjTextField3ActionPerformed

    private void txtDireccionTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionTrabajadoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextPane TextAreaTrabajadores;
    public javax.swing.JButton btnAgregarTrabajadores;
    public javax.swing.JButton btnEliminarTrabajadores;
    public javax.swing.JButton btnGuardarTrabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTableTrabajadores;
    public javax.swing.JPanel panelClienteDatos;
    private javax.swing.JPanel panelListadoCliente;
    private javax.swing.JScrollPane scrollNotaCliente;
    public javax.swing.JScrollPane scrollTableCliente;
    public javax.swing.JTextField txtApellidosTrabajadores;
    public javax.swing.JTextField txtBuscadorTrabajadores;
    public javax.swing.JTextField txtCodigoPTrabajadores;
    public javax.swing.JTextField txtDNITrabajadores;
    public javax.swing.JTextField txtDireccionTrabajadores;
    public javax.swing.JTextField txtEmailTrabajadores;
    public javax.swing.JTextField txtFechaITrabajadores;
    public javax.swing.JTextField txtFechaTrabajadores;
    public javax.swing.JTextField txtMovilTrabajadores;
    public javax.swing.JTextField txtNombreTrabajadores;
    public javax.swing.JTextField txtProvinciaTrabajadores;
    public javax.swing.JTextField txtSalarioTrabajadores;
    public javax.swing.JTextField txtTelefonoTrabajadores;
    // End of variables declaration//GEN-END:variables
}
